# Autogenerated wrapper script for Qt6Svg_jll for x86_64-apple-darwin
export libqt6svg, libqt6svgwidgets

using Qt6Base_jll
JLLWrappers.@generate_wrapper_header("Qt6Svg")
JLLWrappers.@declare_library_product(libqt6svg, "@rpath/QtSvg")
JLLWrappers.@declare_library_product(libqt6svgwidgets, "@rpath/QtSvgWidgets")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll)
    JLLWrappers.@init_library_product(
        libqt6svg,
        "lib/QtSvg.framework/Versions/A/QtSvg",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6svgwidgets,
        "lib/QtSvgWidgets.framework/Versions/A/QtSvgWidgets",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
